# Generated by Django 3.2.9 on 2022-08-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField()),
                ('app_status', models.IntegerField(default=0)),
                ('app_time', models.TimeField()),
                ('app_desc', models.CharField(max_length=30)),
                ('client_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('fb_title', models.CharField(max_length=45)),
                ('fb_desc', models.TextField()),
                ('fb_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallary_img', models.ImageField(upload_to='Gallary')),
            ],
        ),
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('gender', models.BooleanField(default='Not Specified')),
                ('dob', models.DateField(default='Not Specified')),
                ('cus_add1', models.TextField(blank=True, null=True)),
                ('cus_add2', models.TextField(blank=True, null=True)),
                ('pincode', models.IntegerField()),
                ('cus_phone', models.CharField(max_length=10)),
                ('profile', models.ImageField(max_length=1500, upload_to='profileImages/')),
                ('aboutme', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('bank_details', models.CharField(max_length=255)),
                ('visitor_count', models.IntegerField()),
                ('skype', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('fb', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('ig', models.CharField(max_length=255)),
                ('yt', models.CharField(max_length=255)),
                ('gps', models.CharField(max_length=255)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.city')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=15)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.country')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('product_img', models.ImageField(upload_to='ProductImg/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.userbase')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('com_desc', models.CharField(max_length=200)),
                ('com_date', models.DateField(auto_now=True)),
                ('com_resolve', models.BooleanField(default=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
                ('userbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.userbase')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=25)),
                ('comp_add', models.CharField(max_length=45)),
                ('comp_phone', models.CharField(max_length=10)),
                ('comp_email', models.EmailField(max_length=50)),
                ('contact_person', models.CharField(max_length=45)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.state'),
        ),
    ]
