# Generated by Django 3.2.9 on 2022-08-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', models.ImageField(upload_to='Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Mypackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_expire_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=70)),
                ('package_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img', models.ImageField(upload_to='ServiceImg/')),
                ('service_name', models.CharField(max_length=70)),
                ('service_desc', models.CharField(max_length=70)),
                ('status', models.CharField(default='active', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='city_id',
        ),
        migrations.DeleteModel(
            name='Gallary',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='app_desc',
            new_name='app_title',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_email',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cards.userbase'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='fb',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(True, 'Male'), (False, 'Female'), (None, 'Not Specified')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='gps',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='ig',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='linkedin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='skype',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='twitter',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='yt',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='services',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.userbase'),
        ),
        migrations.AddField(
            model_name='mypackage',
            name='package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.package'),
        ),
        migrations.AddField(
            model_name='mypackage',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.userbase'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.userbase'),
        ),
    ]
