# Generated by Django 3.2.9 on 2022-08-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20220826_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.JSONField(default="{'demo':'demo'}"),
        ),
    ]
