# Generated by Django 3.2.9 on 2022-08-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_generateotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='generateotp',
        ),
    ]
