# Generated by Django 3.2.9 on 2022-08-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_delete_generateotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='gender',
        ),
    ]
