# Generated by Django 3.2.9 on 2022-08-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20220826_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='wp',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
    ]
