# Generated by Django 3.2.9 on 2022-08-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_userbase_wp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_name',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.CharField(default='Active', max_length=15),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_img',
            field=models.ImageField(upload_to='Gallery/'),
        ),
    ]
