# Generated by Django 3.2.9 on 2022-08-28 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_feedback_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vgallery_name', models.CharField(max_length=20)),
                ('vgallery_link', models.CharField(max_length=250)),
                ('status', models.CharField(default='Active', max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.userbase')),
            ],
        ),
    ]
