# Generated by Django 3.2.9 on 2022-08-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_vgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='paymentQR',
            field=models.ImageField(blank=True, default=' ', max_length=255, null=True, upload_to='ORs/'),
        ),
    ]
