# Generated by Django 3.2.9 on 2022-08-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_userbase_paymentqr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='com_resolve',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='product_id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='client_mail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='aboutme',
            field=models.CharField(blank=True, default=' ', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='bank_details',
            field=models.CharField(blank=True, default=' ', max_length=1500, null=True),
        ),
    ]
