# Generated by Django 3.2.9 on 2022-10-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_alter_userbase_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('client_image', models.ImageField(upload_to='Testimonials/')),
                ('test_title', models.CharField(max_length=45)),
                ('test_desc', models.TextField()),
                ('test_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cards.userbase')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
